---
- name: Install Nginx
  apt:
    name: nginx
    state: installed
    update_cache: true
  notify:
  - Start Nginx

- name: Create Vhosts Directory
  file:
    path: '{{ nginx_vhosts }}'
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Disable Default Site Configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Install vhosts
  block:
    - template: src=01_example.com.j2 dest=/etc/nginx/vhosts/01_example.com
      notify:
      - Restart Nginx
    - template: src=02_wiki.example.com.j2 dest=/etc/nginx/vhosts/02_wiki_example.com
      notify:
      - Restart Nginx
    - template: src=03_nagios.example.com.j2 dest=/etc/nginx/vhosts/03_nagios.example.com
      notify:
      - Restart Nginx

- name: Install config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - Restart Nginx
